### PR TITLE
fix: use iarna/toml instead of toml

### PR DESCRIPTION
**Pull request by ruben-arts**
Using a better toml parser: https://shared.by.re-becca.org/misc/TOML-SPEC-SUPPORT.html

Fixes a known issue were the following table doesn't work but is valid toml:
```toml
[tool.pixi]
dependencies.boltons = "*"
```

### CODE REVIEW

**Comment by pavelzw** [comment]
You need to add this library to the tsup config

**Comment by pavelzw** [comment]
I think we should wrap the readfile and parse toml in a try catch and do core.error if we catch something
https://github.com/prefix-dev/setup-pixi/blob/b68487257f97d9a4b31dea6e468a50fc1bca2ca6/src/options.ts#L211

The issue was a bit annoying to spot right now.

**Comment by ruben-arts** [comment]
Is an `core.error` enough or should we add more info to it?

**Comment by pavelzw** [comment]
I would add core.error("failed to parse pyproject.toml") and then throw the error again s.t. we see where this error was thrown. The previous error message (https://discord.com/channels/1082332781146800168/1082338253925003385/1245052133053829182) was not really helpful

All errors are catched and displayed in the outer most run action part

**Comment by ruben-arts** [comment]
Yeah right! will do.

**Comment by ruben-arts** [comment]
Haha @pavelzw this is why I wanted a `pixi.toml`, I'm to spoiled by it ;) 

https://github.com/prefix-dev/setup-pixi/pull/118/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R354

**Comment by ruben-arts** [comment]
Or should we updated to `pnpm` `9`?

And should I make a patch release?

**Comment by pavelzw** [comment]
Let’s use pnpm 9 and a patch release 👍🏻

**Review by pavelzw — APPROVED** [review]

**Pull request merged**
