### PR TITLE
Fix failing auth tests

### PR DESCRIPTION
**Pull request by pavelzw**

### CODE REVIEW

**Comment by wolfv** [comment]
Could it be related to the `netrc` supprot that was merged in `rattler`? :/

**Comment by pavelzw** [comment]
Nah probably just @0xbe7a's rattler auth changes. The file name changed from rattler_auth_store.json to credentials.json

**Comment by 0xbe7a** [comment]
Rattler 0.16.1 fixes this

**Comment by pavelzw** [comment]
Seems to work again 🚀

**Pull request merged**
